// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Inventory.Data;

#nullable disable

namespace Web_Inventory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Inventory.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 8,
                            ProductName = "Ball Pen",
                            Quantity = 150,
                            TotalPrice = 1200
                        },
                        new
                        {
                            Id = 2,
                            Price = 400,
                            ProductName = "Matric Math Book",
                            Quantity = 50,
                            TotalPrice = 20000
                        },
                        new
                        {
                            Id = 3,
                            Price = 7,
                            ProductName = "Pencil",
                            Quantity = 500,
                            TotalPrice = 3500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
